apiVersion: v1
kind: Service
metadata:
  namespace: payment-service
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
  
    - protocol: TCP
      port: 4565
      targetPort: 4565
   
   
  selector:
    app: payment-service
  type: ClusterIP
